"""
Constantes do Agno SDK para Gabi
"""

PYTHONPATH_ENV_VAR: str = "PYTHONPATH"
AGNO_RUNTIME_ENV_VAR: str = "AGNO_RUNTIME"
AGNO_API_KEY_ENV_VAR: str = "AGNO_API_KEY"

WORKSPACE_ID_ENV_VAR: str = "AGNO_WORKSPACE_ID"
WORKSPACE_NAME_ENV_VAR: str = "AGNO_WORKSPACE_NAME"
WORKSPACE_ROOT_ENV_VAR: str = "AGNO_WORKSPACE_ROOT"
WORKSPACE_DIR_ENV_VAR: str = "AGNO_WORKSPACE_DIR"
REQUIREMENTS_FILE_PATH_ENV_VAR: str = "REQUIREMENTS_FILE_PATH"

AWS_REGION_ENV_VAR: str = "AWS_REGION"
AWS_DEFAULT_REGION_ENV_VAR: str = "AWS_DEFAULT_REGION"
AWS_PROFILE_ENV_VAR: str = "AWS_PROFILE"

# Constantes específicas do Gabi
GABI_SESSION_MAX_AGENTS: int = 3
GABI_SESSION_MAX_ORCHESTRATOR: int = 1
GABI_MAX_KB_SOURCES: int = 10

# Tipos de agentes
AGENT_TYPE_AGENT = "agent"
AGENT_TYPE_ORCHESTRATOR = "orchestrator"

# Tipos de fontes de conhecimento
KB_TYPE_RAG = "rag"
KB_TYPE_WEBSITE = "website"
KB_TYPE_DOCUMENT = "document"
KB_TYPE_MCP = "mcp"

# Status
STATUS_ACTIVE = "active"
STATUS_INACTIVE = "inactive"
STATUS_ERROR = "error"
STATUS_PENDING = "pending"
