services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: gabi-clean-dashboard
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    stdin_open: true
    tty: true
    restart: unless-stopped

